; X/Y Position auf der Mittelmeerkarte (0,0 = links unten; Karte hat Größe 537x251)
; Jede Stadt hat 2 Import und 2 Exportwaren
; Die Distanz ist die Distanz in Tagen ausgehend vom Ärmelkanal

[Map]
MapSizeX = 537
MapSizeY = 251

ExplorationDist = 25
DefaultDuration = 1

IconPosX = 100
IconPosY = 460

[Regions]
Number = 5

[Expedition00]
XPos = 78 ; Position auf der Expeditionskarte
YPos = 153
ImportA = 8 ; Nr. der Ware
ImportB = 15
ExportA = 19
ExportB = 18
Distance = 9 ; Entfernung zur Hanse
Region = 0 ; pro Spiel wird aus jeder Region eine Stadt gewählt

[Expedition01]
XPos = 111
YPos = 142
ImportA = 8
ImportB = 15
ExportA = 19
ExportB = 18
Distance = 10
Region = 0

[Expedition02]
XPos = 138
YPos = 99
ImportA = 8
ImportB = 15
ExportA = 19
ExportB = 18
Distance = 12
Region = 0

[Expedition03]
XPos = 145
YPos = 82
ImportA = 8
ImportB = 15
ExportA = 19
ExportB = 18
Distance = 13
Region = 0

[Expedition04]
XPos = 171
YPos = 73
ImportA = 8
ImportB = 15
ExportA = 19
ExportB = 18
Distance = 14
Region = 0

[Expedition05]
XPos = 205
YPos = 59
ImportA = 15
ImportB = 8
ExportA = 19
ExportB = 18
Distance = 15
Region = 1

[Expedition06]
XPos = 235
YPos = 92
ImportA = 15
ImportB = 8
ExportA = 19
ExportB = 18
Distance = 15
Region = 1

[Expedition07]
XPos = 255
YPos = 106
ImportA = 15
ImportB = 8
ExportA = 19
ExportB = 18
Distance = 16
Region = 1

[Expedition08]
XPos = 244
YPos = 140
ImportA = 15
ImportB = 8
ExportA = 19
ExportB = 18
Distance = 15
Region = 1

[Expedition09]
XPos = 275
YPos = 103
ImportA = 15
ImportB = 8
ExportA = 19
ExportB = 18
Distance = 17
Region = 1

[Expedition10]
XPos = 274
YPos = 71
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 18
Distance = 17
Region = 2

[Expedition11]
XPos = 337
YPos = 139
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 18
Distance = 19
Region = 2

[Expedition12]
XPos = 392
YPos = 102
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 18
Distance = 21
Region = 2

[Expedition13]
XPos = 374
YPos = 137
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 18
Distance = 20
Region = 2

[Expedition14]
XPos = 407
YPos = 153
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 18
Distance = 22
Region = 2

[Expedition15]
XPos = 422
YPos = 219
ImportA = 8
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 22
Region = 3

[Expedition16]
XPos = 402
YPos = 221
ImportA = 8
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 22
Region = 3

[Expedition17]
XPos = 347
YPos = 211
ImportA = 8
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 19
Region = 3

[Expedition18]
XPos = 309
YPos = 212
ImportA = 8
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 18
Region = 3

[Expedition19]
XPos = 244
YPos = 202
ImportA = 8
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 15
Region = 3

[Expedition20]
XPos = 219
YPos = 178
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 14
Region = 4

[Expedition21]
XPos = 215
YPos = 156
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 14
Region = 4

[Expedition22]
XPos = 146
YPos = 157
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 11
Region = 4

[Expedition23]
XPos = 113
YPos = 168
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 10
Region = 4

[Expedition24]
XPos = 90
YPos = 176
ImportA = 15
ImportB = 16
ExportA = 19
ExportB = 10
Distance = 9
Region = 4

[Portsize]
Factor = 0.25
