[Science]
; Format: Nummer, interner Name, Nr. Voraussetzung 1, Nr. Voraussetzung 2, benötigte FP
science0_0 = 0, Dreifelderwirtschaft, -1 ,-1, 100
science0_1 = 1, Arbeitsteilung, 0 ,-1, 200
science0_2 = 2, Lagerhaltung, -1 ,-1, 300
science1_0 = 0, Kartografie, -1 ,-1, 300
science1_1 = 1, Städtegründung, -1 ,-1, 50
science2_0 = 0, Holk, -1 ,-1, 50
science2_1 = 1, Hansekogge, 0 ,-1, 100
science2_2 = 2, Flusskogge, 0 ,-1, 100
science2_3 = 3, Kraveel, 1 ,2, 300
science3_0 = 0, Ballistik, -1 ,-1, 50
science3_1 = 1, Gekörntes Pulver, 0 ,-1, 200
science3_2 = 2, Gefechtssegel, -1 ,-1, 100
science4_0 = 0, Wachturm, -1 ,-1, 20
science4_1 = 1, Kanonenturm, 0 ,-1, 100
science4_2 = 2, Bauhandwerk, 0 ,-1, 300

[TimeSteps]
; PreSteps = 0

[Reputation]
Offset = 0.8, 0.72, 0.63, 0.4
Amplitude = 0.1, 0.2, 0.1, 0.1
Phase = 7.0, 4.4, 2.8, 1.6
[GuildMembership]
gms0 = 0, -1.0, 0
gms1 = 1, 0.25, 2
gms2 = 2, 0.3, 4
gms3 = 3, 0.35, 5
gms4 = 4, 0.4, 6
gms5 = 5, 0.5, 7
gms6 = 6, 0.6, 7

[GuildPrivilege]
priv0 = 0, 0.0, 0
priv1 = 1, 0.4, 2
priv2 = 2, 0.5, 3
priv3 = 3, 0.6, 4

[StandardPaymentValue]
spv0 =	0, 1000
spv1 =	80000, 2000
spv2 =	150000, 5000
spv3 =	300000, 10000
spv4 =	500000, 20000
spv5 =	800000, 30000
spv6 =	1100000, 40000
spv7 =	1500000, 50000
spv8 =	2200000, 60000
spv9 =	3200000, 70000
spv10 =	5000000, 100000
spv11 =	10000000, 200000

[GameSpeed]
StepLimit = 2000
GAMESPEED_0_1 = 1
GAMESPEED_1 = 10
GAMESPEED_5 = 50
GAMESPEED_10 = 100
GAMESPEED_99 = 1000
; battle speeds in 1/10th
BATTLESPEED_1 =	2
BATTLESPEED_2 = 4
BATTLESPEED_3 = 6
BATTLESPEED_4 = 10
BATTLESPEED_5 = 20


[Weather]

DROUGHT = 255
SUN0 = 12
SUN1 = 12
CLOUDY0 = 12
CLOUDY1 = 6
RAIN = 3
STORMY = 255
ICESUN = 12
ICECLOUD = 12
SNOW = 3
SNOWSTORM = 255

zone0change = 69, 155, 277, 365
zone1change = 70, 158, 274, 362
zone2change = 73, 161, 271, 359
zone3change = 76, 164, 268, 356
zone4change = 79, 167, 265, 353

zone0ice =  5 ; 0 .. 1000
zone1ice = 10
zone2ice = 12
zone3ice = 14
zone4ice = 16

zone0storm = 10 ; 0 .. 1000
zone1storm = 10
zone2storm = 10
zone3storm = 10
zone4storm = 10

zone0drought = 10 ; 0 .. 1000
zone1drought = 10
zone2drought = 10
zone3drought = 10
zone4drought = 10

Spring = 2, 3, 4, 5
Summer = 1, 2, 5
Autumn = 3, 4, 5
Winter = 7, 8, 9

[Donation]
Ansehen = 0.01
Pay = 10
Steps = 2
MaxSteps = 20

[Advisor]
hint0 = 3
hint1 = 5
hint2 = 10
hint3 = 15

[GameStart]
Year = 1370
Month = 4
Day = 1

[NewGame]
TownSize0	= 2000
TownSize1	= 2500
TownSize2	= 3000
TownSet0	= 20
TownSet1	= 21
TownSet2	= 22
TownSet3	= 23
TownSet4	= 24
TownSet5	= 25
TownSet6	= 26
Emblems		= 13
Avatars		= 16

[Difficulty]
RepFactor	= 1.0, 0.75, 0.5

[Autosave]
Filename = p4auto.p4s

[Abwanderung]
Arbeiter = 1.0f, 1.0f, 1.0f
Bettler = 0.1f, 0.22f, 0.35f
Pesttote = 0.5f, 1.0f, 1.5f

[Lebensqualitaet]
EventElq = 39.0

[SpecialEdition]
InitialShip = 7 ; (Spezialkogge)
OfficeAsset = office
OfficeAssetSp = office_special

[Verbrauch]
Pest = 100
Ratten = 100
Feuer = 100
Rattenstart = 10, 30, 50

[Scenarios]
Order = 1, 6, 5, 4, 2, 3
Scenario1 =   0,   0,   0,   0,   0,   0
Scenario2 =  50,   0,   0,  50,  50,  50
Scenario3 =  50, 100,   0,  50,  50,  50
Scenario4 =   0,   0,   0,   0,   0,   0
Scenario5 =   0,   0,   0,   0,   0,   0
Scenario6 =   0,   0,   0,   0,   0,   0