[Time]
StepsPerSec		= 20	; Zeitschritte pro Sekunde bei normaler Geschwindigkeit
SpeedFactor		= 1.0	; globaler Zeitfaktor, mit dem alle Geschwindigkeiten angepasst werden können ; DO NOT USE !!! IT'S IGNORED ANYWAY

[Weather]
CloudLayer		= seabattleclouds

[Battleship]
MaxTurn			= 45	; Basis für maximale Winkeländerung in ° pro Sekunde
MaxAccel		= 4	; maximale Beschleunigung in m/s^2 bei 100% Wendigkeit
ReloadTime		= 5	; Standardnachladedauer in s
ReloadFactor		= 0.25	; Zeitfaktor für die Nachladedauer in Abh. der Matrosenzahl
MaxInclination		= 5	; Maximaler Neigungswinkel um die Längsachse
NavigationFactor	= 0.05	; Faktor für Navigationsskill
TurnSpeedFactor		= 0.3	; Faktor in der Berechnung der maximalen Winkeländerung
SinkSpeed		= -0.01 ; SinkSpeed

[AmmoTrajectory]
Gravity			= 10	; Erdbschleunigung in m/s^2
Amax			= 10	; Maximaler Abschusswinkel in °
ACorrMax		= 5	; maximaler Korrekturwinkel in °
FiringDelay		= 50	; maximale Schussverzögerung in ms
ScatterMin		= 0.98	; minimaler Störfaktor für Geschwindigkeitskomponenten
ScatterMax		= 1.02	; maximaler Störfaktor für Geschwindigkeitskomponenten

[AmmoData]
; alle Schadens- und Hüllenwertewerte aus dem Konzept * 1000
Vmax_0			= 70	; Maximale Geschwindigkeit von Massivkugeln in m/s
Vmax_1			= 65	; Maximale Geschwindigkeit von Kettenkugeln in m/s
Vmax_2			= 60	; Maximale Geschwindigkeit von Schrotmunition in m/s
DmgHull_0		= 1000	; Schaden am Rumpf für Massivkugeln
DmgHull_1		= 200	; Schaden am Rumpf für Kettenkugeln
DmgHull_2		= 300	; Schaden am Rumpf für Schrot
DmgSail_0		= 100	; Schaden an Segeln für Massivkugeln
DmgSail_1		= 1500	; Schaden an Segeln für Kettenkugeln
DmgSail_2		= 100	; Schaden an Segeln für Schrot
DmgCrew_0		= 300	; Mannschaftsverluste für Massivkugeln
DmgCrew_1		= 100	; Mannschaftsverluste für Kettenkugeln
DmgCrew_2		= 1200	; Mannschaftsverluste für Schrot
Asset_0			= cannonball0
Asset_1			= cannonball0
Asset_2			= cannonball0

[HullDamage]
Condition_0		= 0.8	; Zustandswert des Rumpfes in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_1		= 0.6	; Zustandswert des Rumpfes in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_2		= 0.4	; Zustandswert des Rumpfes in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_3		= 0.2	; Zustandswert des Rumpfes in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
SpeedFactor_0		= 1.0	; Geschwindigkeitsfaktor
SpeedFactor_1		= 0.9	; Geschwindigkeitsfaktor
SpeedFactor_2		= 0.8	; Geschwindigkeitsfaktor
SpeedFactor_3		= 0.7	; Geschwindigkeitsfaktor
DmgState_0		= 1	; Zerstörungsstufe für Schadensanzeige
DmgState_1		= 2	; Zerstörungsstufe für Schadensanzeige
DmgState_2		= 3	; Zerstörungsstufe für Schadensanzeige
DmgState_3		= 4	; Zerstörungsstufe für Schadensanzeige

[SailDamage]
Condition_0		= 0.75	; Zustandswert der Segel in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_1		= 0.50	; Zustandswert der Segel in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_2		= 0.25	; Zustandswert der Segel in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
Condition_3		= 0.0	; Zustandswert der Segel in % (0..1) ab dem die Geschwindigkeitseinbuße gilt
SpeedFactor_0		= 0.9	; Geschwindigkeitsfaktor
SpeedFactor_1		= 0.8	; Geschwindigkeitsfaktor
SpeedFactor_2		= 0.6	; Geschwindigkeitsfaktor
SpeedFactor_3		= 0.5	; Geschwindigkeitsfaktor
DmgState_0		= 1	; Zerstörungsstufe für Schadensanzeige
DmgState_1		= 2	; Zerstörungsstufe für Schadensanzeige
DmgState_2		= 3	; Zerstörungsstufe für Schadensanzeige
DmgState_3		= 4	; Zerstörungsstufe für Schadensanzeige

[Attraction]
A0	=	1.0
B0	=	1.0
C0	=	1.0
D0	=	1.0
E0	=	1.0

A1	=	1.5
B1	=	1.0
C1	=	1.0
D1	=	1.0

[Tactic]
MaxFleeDist = 1000.0
ProtectionRadius = 100.0