; -----------------------------------------------------------------------------
; alle Schadens- und HPwerte aus dem Konzept * 1000
; -----------------------------------------------------------------------------

[Constants]
FactorKnotToMeter	= 4

; -----------------------------------------------------------------------------
; Schnigge
; -----------------------------------------------------------------------------
[Ship00] 
Capacity	= 200	; Laderaum in Fass
Vmin		= 16	; Min-Geschwindigkeit in Seeschlachten in m/s
Vmax		= 27	; Max-Geschwindigkeit in Seeschlachten in m/s
Wendig		= 100	; Wendigkeit in %
Fluss		= 3	; 1 == Meer, 2 == Fluss, 3 = beides
Ausbau		= 2	; Anzahl der Ausbaumöglichkeiten
MaxHp		= 50000	; maximale HP der Grundstufe (* 1000 gegenüber Konzept)
MaxSailHp	= 50000	; maximale HP der Grundstufe (* 1000 gegenüber Konzept)
Goods		= 0, 40, 3, 10, 8, 10, 10, 10, 15, 10 ; Bauwaren mit Warennummer und Menge in Fass
Costs		= 10000 ; Baukosten in GS
MatCosts	= 6000	; Materialkosten der Schnigge in GS
BattleAsset	= schnigge
SeaMapAsset	= schnigge_wm
DailyCosts	= 20	; Grundkosten in GS pro Tag wenn bei Stichzeit auf See
Initial		= 1	; Schiffstyp muss nicht erforscht werden
SailType0	= 2	; Die Werte für Segel, Hull und Guns sollten nicht geändert werden!
SailTrans0  	= refl_0
SailType1	= 2
SailTrans1  	= refl_1
SailType2	= 3
SailTrans2  	= refl_2
SailType3   	= 3
SailTrans3  	= refl_3

Hull0Length 	= -10.5, 5.5, 9
Hull0Width	= 2.75, 2.75
Hull0Height 	= 3
Sail0Offset	= 0, 7
Sail0Length	= 8, 15
Sail0Height 	= 16, 12
Sail0Type	= 0, 1

Hull1Length 	= -10.5, 5.5, 9
Hull1Width	= 2.75, 2.75
Hull1Height 	= 3
Sail1Offset	= 0, 7
Sail1Length	= 8, 15
Sail1Height 	= 12
Sail1Type	= 0, 1

Hull2Length 	= -10.5, 5.5, 9
Hull2Width	= 2.75, 2.75
Hull2Height 	= 3
Sail2Offset	= 0, 7
Sail2Length	= 8, 15
Sail2Height 	= 16, 12
Sail2Type	= 0, 1

Gun1Pos0 = 2.8, 3.2,  2
Gun1Pos1 = 2.8, 3.2,  0
Gun1Pos2 = 2.8, 3.2, -2

Gun2Pos0 = 2.8, 3.2,  2
Gun2Pos1 = 2.8, 3.2,  0
Gun2Pos2 = 2.8, 3.2, -2
Gun2Pos3 = 2.8, 3.2, -4
Gun2Pos4 = 2.8, 3.2, -6

CapacityLoss1 = 6
CapacityLoss2 = 12

; -----------------------------------------------------------------------------
; Kraier
; -----------------------------------------------------------------------------
[Ship01]
Capacity	= 300
Vmin		= 20
Vmax		= 28
Wendig		= 90
Fluss		= 3
Ausbau		= 2
MaxHp		= 75000
MaxSailHp	= 75000
Goods		= 0, 60, 3, 20, 8, 20, 10, 20, 15, 20
Costs		= 15000
MatCosts	= 11333		; Materialkosten des Kraiers in GS
BattleAsset	= kraier
SeaMapAsset	= kraier_wm
DailyCosts	= 30
Initial		= 1

SailType0	= 2
SailTrans0  	= refl_0
SailType1	= 2
SailTrans1  	= refl_5
SailType2	= 2
SailTrans2  	= refl_6
SailType3   	= 2
SailTrans3  	= refl_1
SailType4	= 2
SailTrans4  	= refl_4
SailType5	= 2
SailTrans5  	= refl_3
SailType6	= 3
SailTrans6  	= refl_7

Hull0Length 	= -10.5, 5.5, 9
Hull0Width	= 2.75, 2.75
Hull0Height 	= 3
Sail0Offset	= 0, 10
Sail0Length	= 10, 19
Sail0Height 	= 20, 20
Sail0Type	= 0, 1

Hull1Length 	= -10.5, 5.5, 9
Hull1Width	= 2.75, 2.75
Hull1Height 	= 3
Sail1Offset	= 0, 10
Sail1Length	= 10, 19
Sail1Height 	= 20, 20
Sail1Type	= 0, 1

Hull2Length 	= -10.5, 5.5, 9
Hull2Width	= 2.75, 2.75
Hull2Height 	= 3
Sail2Offset	= 0, 10
Sail2Length	= 10, 19
Sail2Height 	= 20, 20
Sail2Type	= 0, 1

Gun1Pos0 = 2.8, 3.2,  2
Gun1Pos1 = 2.8, 3.2,  0
Gun1Pos2 = 2.8, 3.2, -2
Gun1Pos3 = 2.8, 3.2, -4

Gun2Pos0 = 2.8, 3.2,  2
Gun2Pos1 = 2.8, 3.2,  0
Gun2Pos2 = 2.8, 3.2, -2
Gun2Pos3 = 2.8, 3.2, -4
Gun2Pos4 = 2.8, 3.2, -8
Gun2Pos5 = 2.8, 3.2, -10
Gun2Pos6 = 2.8, 3.2, -12

CapacityLoss1 = 8
CapacityLoss2 = 16

; -----------------------------------------------------------------------------
; Kogge
; -----------------------------------------------------------------------------
[Ship02]
Capacity	= 500
Vmin		= 16
Vmax		= 24
Wendig		= 80
Fluss		= 1
Ausbau		= 2
MaxHp		= 125000
MaxSailHp	= 125000
Goods		= 0, 100, 3, 30, 8, 30, 10, 30, 15, 30
Costs		= 25000
MatCosts	= 17333				; Materialkosten der Kogge in GS
BattleAsset	= kogge
SeaMapAsset	= kogge_wm
DailyCosts	= 50
Initial		= 1

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_1

Hull0Length 	= -12.5, 5.5, 13.5
Hull0Width	= 2.75, 4.25
Hull0Height 	= 5
Sail0Offset	= 0, 8
Sail0Length	= 16, 16
Sail0Height 	= 24, 24
Sail0Type	= 0, 1

Hull1Length 	= -12.5, 5.5, 13.5
Hull1Width	= 2.75, 4.25
Hull1Height 	= 5
Sail1Offset	= 0, 8
Sail1Length	= 16, 16
Sail1Height 	= 24, 24
Sail1Type	= 0, 1

Hull2Length 	= -12.5, 5.5, 13.5
Hull2Width	= 2.75, 4.25
Hull2Height 	= 5
Sail2Offset	= 0, 8
Sail2Length	= 16, 16
Sail2Height 	= 24, 24
Sail2Type	= 0, 1

Gun1Pos0 = 2.8, 3.2,  2
Gun1Pos1 = 2.8, 3.2,  0
Gun1Pos2 = 2.8, 3.2, -2
Gun1Pos3 = 2.8, 3.2, -4
Gun1Pos4 = 2.8, 3.2, -6
Gun1Pos5 = 2.8, 3.2, -8

Gun2Pos0 = 2.8, 3.2,  2
Gun2Pos1 = 2.8, 3.2,  1
Gun2Pos2 = 2.8, 3.2, -1
Gun2Pos3 = 2.8, 3.2, -2
Gun2Pos4 = 2.8, 3.2, -3
Gun2Pos5 = 2.8, 3.2, -4
Gun2Pos6 = 2.8, 3.2, -5
Gun2Pos7 = 2.8, 3.2, -6
Gun2Pos8 = 2.8, 3.2, -7
Gun2Pos9 = 2.8, 3.2, -8

CapacityLoss1 = 12
CapacityLoss2 = 24

; -----------------------------------------------------------------------------
; Holk
; -----------------------------------------------------------------------------
[Ship03]
Capacity	= 650
Vmin		= 16
Vmax		= 29
Wendig		= 70
Fluss		= 1
Ausbau		= 2
MaxHp		= 160000
MaxSailHp	= 160000
Goods		= 0, 120, 3, 40, 8, 40, 10, 40, 15, 40
Costs		= 32500
MatCosts	= 22666					; Materialkosten des Holks in GS
BattleAsset	= holk
SeaMapAsset	= holk_wm
DailyCosts	= 65

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_2
SailType2	= 0
SailTrans2  	= refl_1
SailType3   	= 1
SailTrans3  	= refl_3

Hull0Length 	= -18.0, 8.0, 13.5
Hull0Width	= 4.0, 4.25
Hull0Height 	= 5
Sail0Offset	= 6, -4, 11
Sail0Length	= 10, 16, 26
Sail0Height 	= 22, 22, 22
Sail0Type	= 0, 0, 1

Hull1Length 	= -18.0, 8.0, 13.5
Hull1Width	= 4.0, 4.25
Hull1Height 	= 5
Sail1Offset	= 6, -4, 11
Sail1Length	= 10, 16, 26
Sail1Height 	= 22, 22, 22
Sail1Type	= 0, 0, 1

Hull2Length 	= -18.0, 8.0, 13.5
Hull2Width	= 4.0, 4.25
Hull2Height 	= 5
Sail2Offset	= 6, -4, 11
Sail2Length	= 10, 16, 26
Sail2Height 	= 22, 22, 22
Sail2Type	= 0, 0, 1

Gun1Pos0 = 2.8, 3.2,  2
Gun1Pos1 = 2.8, 3.2,  0
Gun1Pos2 = 2.8, 3.2, -2
Gun1Pos3 = 2.8, 3.2, -4
Gun1Pos4 = 2.8, 3.2, -6
Gun1Pos5 = 2.8, 3.2, -8
Gun1Pos6 = 2.8, 3.2, -10

Gun2Pos0 = 2.8, 3.2,  2
Gun2Pos1 = 2.8, 3.2,  1
Gun2Pos2 = 2.8, 3.2, -1
Gun2Pos3 = 2.8, 3.2, -2
Gun2Pos4 = 2.8, 3.2, -3
Gun2Pos5 = 2.8, 3.2, -4
Gun2Pos6 = 2.8, 3.2, -5
Gun2Pos7 = 2.8, 3.2, -6
Gun2Pos8 = 2.8, 3.2, -7
Gun2Pos9 = 2.8, 3.2, -8
Gun2Pos10 = 2.8, 3.2, -9
Gun2Pos11 = 2.8, 3.2, -10

CapacityLoss1 = 14
CapacityLoss2 = 28

; -----------------------------------------------------------------------------
; Hansekogge
; -----------------------------------------------------------------------------
[Ship04]
Capacity	= 1000
Vmin		= 16
Vmax		= 24
Wendig		= 60
Fluss		= 1
Ausbau		= 0
MaxHp		= 250000
MaxSailHp	= 250000
Goods		= 0, 200, 3, 50, 8, 50, 10, 50, 15, 50
Costs		= 50000
MatCosts	= 30000									; Materialkosten der Hansekogge in GS
BattleAsset	= hansekogge
SeaMapAsset	= hansekogge_wm
DailyCosts	= 100

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_1

SailType2	= 0
SailTrans2  	= refl_2
SailType3	= 1
SailTrans3  	= refl_3

SailType4	= 3
SailTrans4  	= refl_4

Hull0Length 	= -12.5, 5.5, 13.5
Hull0Width	= 2.75, 4.25
Hull0Height 	= 5
Sail0Offset	= 0, 8
Sail0Length	= 16, 16
Sail0Height 	= 24, 24
Sail0Type	= 0, 1

; -----------------------------------------------------------------------------
; Flusskogge
; -----------------------------------------------------------------------------
[Ship05]
Capacity	= 1000
Vmin		= 16
Vmax		= 23
Wendig		= 70
Fluss		= 2
Ausbau		= 0
MaxHp		= 250000
MaxSailHp	= 250000
Goods		= 0, 200, 3, 50, 8, 50, 10, 50, 15, 50
Costs		= 50000
MatCosts	= 30000						; Materialkosten der Flusskogge in GS
BattleAsset	= riverkogge
SeaMapAsset	= riverkogge_wm
DailyCosts	= 100

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_1
SailType2	= 3
SailTrans2  	= refl_2

Hull0Length 	= -10.5, 5.5, 9
Hull0Width	= 2.75, 2.75
Hull0Height 	= 3
Sail0Offset	= 0, 10
Sail0Length	= 10, 19
Sail0Height 	= 20, 20
Sail0Type	= 0, 1

; -----------------------------------------------------------------------------
; Kraveel
; -----------------------------------------------------------------------------
[Ship06]
Capacity	= 2000
Vmin		= 24
Vmax		= 31
Wendig		= 50
Fluss		= 1
Ausbau		= 0
MaxHp		= 500000
MaxSailHp	= 500000
Goods		= 0, 400, 3, 100, 8, 100, 10, 100, 15, 100
Costs		= 100000
MatCosts	= 60000				; Materialkosten der Karavelle in GS
BattleAsset	= kraveel
SeaMapAsset	= kraveel_wm
DailyCosts	= 200

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_1
SailType2	= 0
SailTrans2  	= refl_2
SailType3	= 1
SailTrans3  	= refl_3
SailType4	= 0
SailTrans4  	= refl_4
SailType5	= 1
SailTrans5  	= refl_5
SailType6	= 0
SailTrans6  	= refl_8
SailType7	= 1
SailTrans7  	= refl_9
SailType8	= 0
SailTrans8  	= refl_12
SailType9	= 1
SailTrans9  	= refl_13
SailType10	= 0
SailTrans10 	= refl_14
SailType11	= 1
SailTrans11 	= refl_15

; -----------------------------------------------------------------------------
; SpecialEdition ship
; -----------------------------------------------------------------------------
[Ship07]
Capacity	= 5000
Vmin		= 70
Vmax		= 70
Wendig		= 100
Fluss		= 3
Ausbau		= 2
MaxHp		= 925000
MaxSailHp	= 925000
Goods		= 0, 40, 3, 10, 8, 10, 10, 10, 15, 10
Costs		= 10000
MatCosts	= 6000				; Materialkosten der Kogge in GS
BattleAsset	= kogge_special
SeaMapAsset	= kogge_wm
DailyCosts	= 1
Initial		= 0

SailType0	= 0
SailTrans0  	= refl_0
SailType1	= 1
SailTrans1  	= refl_1

Hull0Length 	= -12.5, 5.5, 13.5
Hull0Width	= 2.75, 4.25
Hull0Height 	= 5
Sail0Offset	= 0, 8
Sail0Length	= 16, 16
Sail0Height 	= 24, 24
Sail0Type	= 0, 1

Hull1Length 	= -12.5, 5.5, 13.5
Hull1Width	= 2.75, 4.25
Hull1Height 	= 5
Sail1Offset	= 0, 8
Sail1Length	= 16, 16
Sail1Height 	= 24, 24
Sail1Type	= 0, 1

Hull2Length 	= -12.5, 5.5, 13.5
Hull2Width	= 2.75, 4.25
Hull2Height 	= 5
Sail2Offset	= 0, 8
Sail2Length	= 16, 16
Sail2Height 	= 24, 24
Sail2Type	= 0, 1

Gun1Pos0 = 2.8, 3.2,  2
Gun1Pos1 = 2.8, 3.2,  0
Gun1Pos2 = 2.8, 3.2, -2
Gun1Pos3 = 2.8, 3.2, -4
Gun1Pos4 = 2.8, 3.2, -6
Gun1Pos5 = 2.8, 3.2, -8

Gun2Pos0 = 2.8, 3.2,  2
Gun2Pos1 = 2.8, 3.2,  1
Gun2Pos2 = 2.8, 3.2, -1
Gun2Pos3 = 2.8, 3.2, -2
Gun2Pos4 = 2.8, 3.2, -3
Gun2Pos5 = 2.8, 3.2, -4
Gun2Pos6 = 2.8, 3.2, -5
Gun2Pos7 = 2.8, 3.2, -6
Gun2Pos8 = 2.8, 3.2, -7
Gun2Pos9 = 2.8, 3.2, -8

CapacityLoss1 = 1
CapacityLoss2 = 2